### ISSUE TITLE
Connessione WebServices  ambiente di test

### ISSUE THREAD

**Issue by adrianosicilia** [italia/anpr#2158]
Premesso che abbiamo popolato con qualche migliaia di record tramite la piattaforma web, ora vorremo vedere di consultare tali dati con le chiamate tramite web services, ma lo stesso applicativo maven compilato e funzionante in ambiente free, quando si cerca di effettuare il test di connessione con il certificato e le credenziali validi per la piattaforma web, otteniamo un errore nella connessione al server anpr
Non riesco a capire se l'errore e nelle date on certificato che stiamo usando.
Nota: le password sono chiaramente sostituite con degli asterischi.
Grazie della collaborazione, Adriano Sicilia, per conto del comune di Rende, CS

**questa è la request da inviare:**
<?xml version="1.0"?>
<ns2:RichiestaConnessione xmlns:ns2="http://sogei.it/ANPR/connessione">
<testataRichiesta>
<idOperazioneComune>20200714112500</idOperazioneComune>
<codMittente>078102</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>TEST</operazioneRichiesta>
<dataOraRichiesta>2020-07-14T09:25:00.000+01:00</dataOraRichiesta>
<tipoOperazione>C</tipoOperazione>
<tipoInvio>TEST</tipoInvio>
<nomeApplicativo>Aquarius MAVEN</nomeApplicativo>
<versioneApplicativo>2019.1</versioneApplicativo>
<fornitoreApplicativo>Aquarius sas</fornitoreApplicativo>
</testataRichiesta>
</ns2:RichiestaConnessione>

**e questo è il log dell'errore:**

F:\ANPR_Client>runClient.cmd TEST TESTCONN request\0\0_078102_test.req 

F:\ANPR_Client>java -cp tool-testconn-1.3.0.jar;. it.interno.anpr.security.main.RunSenderMessage TEST TESTCONN request\0\0_078102_test.req  
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [it.interno.anpr] additivity to [false].
log4j: Level value for it.interno.anpr is  [DEBUG].
log4j: it.interno.anpr level set to DEBUG
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n].
log4j: Adding appender named [console] to category [it.interno.anpr].
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Adding appender named [console] to category [root].
2020-07-14 11:26:40 INFO  BusApplicationContext:510 - Refreshing org.apache.cxf.bus.spring.BusApplicationContext@3e9b1010: startup date [Tue Jul 14 11:26:40 CEST 2020]; root of context hierarchy
2020-07-14 11:26:40 INFO  BusApplicationContext:449 - Loaded configuration file cxf.xml.
2020-07-14 11:26:40 INFO  ControlledValidationXmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
2020-07-14 11:26:40 INFO  ControlledValidationXmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [cxf.xml]
2020-07-14 11:26:41 INFO  ReflectionServiceFactoryBean:390 - Creating Service {http://sogei.it/ANPR/TestConn}TestConn from WSDL: jar:file:/F:/ANPR_Client/tool-testconn-1.3.0.jar!/wsdl/testConnettivita.wsdl
2020-07-14 11:26:41 DEBUG ConfigHandler:65 - Key: (URL_WS):https://dptest.anpr.interno.it/combas
2020-07-14 11:26:41 INFO  RequestHandler:58 - ENDPOINT=https://dptest.anpr.interno.it/combas/ANPRTestConn/TestConn
2020-07-14 11:26:41 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.alias):078102-CO-0000
2020-07-14 11:26:41 INFO  TestConnHandler:40 - testConnessione invoke...
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.alias):078102-CO-0000
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (ID_OPERATORE):BLMFNC70P57D086V
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (ID_SEDE):078102
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (ID_POSTAZIONE):078102-CO-0000
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (ID_POSTAZIONE):078102-CO-0000
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (PATH_KEYSTORE_POSTAZIONE):keystore/TEST/078102-CO-0000.p12
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (PASS_KEYSTORE_POSTAZIONE):********
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (ID_APPLICAZIONE):12345
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.alias):078102-CO-0000
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.password):********
2020-07-14 11:26:42 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.password):********
2020-07-14 11:26:43 WARN  PhaseInterceptorChain:449 - Interceptor for {http://sogei.it/ANPR/TestConn}TestConn#{http://sogei.it/ANPR/TestConn}testConnessione has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Problem writing SAAJ model to stream: Received fatal alert: handshake_failure
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:224)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	at com.sun.proxy.$Proxy36.testConnessione(Unknown Source)
	at it.interno.anpr.security.message.TestConnHandler.sendRequest(TestConnHandler.java:41)
	at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:47)
	at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:61)
Caused by: com.ctc.wstx.exc.WstxIOException: Received fatal alert: handshake_failure
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:458)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:777)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:724)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
	... 12 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:236)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1320)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1280)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:267)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
	at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
	at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
	at com.ctc.wstx.sw.BufferingXmlWriter.flushBuffer(BufferingXmlWriter.java:1405)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:281)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:603)
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:456)
	... 15 more
2020-07-14 11:26:43 ERROR TestConnHandler:44 - Exception nell'invio richiesta
javax.xml.ws.soap.SOAPFaultException: Problem writing SAAJ model to stream: Received fatal alert: handshake_failure
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:161)
	at com.sun.proxy.$Proxy36.testConnessione(Unknown Source)
	at it.interno.anpr.security.message.TestConnHandler.sendRequest(TestConnHandler.java:41)
	at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:47)
	at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:61)
Caused by: com.ctc.wstx.exc.WstxIOException: Received fatal alert: handshake_failure
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:458)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:777)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:724)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	... 4 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:236)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1320)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1280)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:267)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
	at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
	at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
	at com.ctc.wstx.sw.BufferingXmlWriter.flushBuffer(BufferingXmlWriter.java:1405)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:281)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:603)
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:456)
	... 15 more

--- TESTO DA ELIMINARE ---

Prima di tutto, grazie per la segnalazione!

Nel campo "Title" (qua sopra), usa "[codice flusso] Breve descrizione del problema".  Per esempio: "[1001] Errore nello specificare stato estero"

Inoltre, non inserire dati sensibili dei cittadini. Evita, per esempio, qualsiasi nome, cognome, o codice fiscale. Non ci sono problemi invece nell'inserire dei codici di richiesta o identificativi di scheda, per esempio.

Se devi inviarci un tracciato con dati sensibili invialo per email a "segnalazioni-anpr@teamdigitale.governo.it", specificando nell'oggetto il codice del bug.

In ogni caso, ricordati di inserire:

   * Una descrizione accurata del comportamento o dell'errore, e come possiamo esservi utile.
   * La data del test, l'ambiente usato (test, pre-subentro, subentro), e codici di richiesta
     o identificativi che possiamo usare per verificare il sistema.
   * Chi siete e il comune per cui lavorate.

Per il resto, ricordati che puoi scrivere in **grassetto**, inserire dell'XML:

```xml
<xml>
  <example>

  </example>
</xml>
```

... oppure elenchi puntati:

   * punto
   * punto

... o titoli:

### Esempio titolo

--- TESTO DA ELIMINARE ---

**Comment by gife67** [comment]
Buongiorno,
l'endpoint dei servizi di ANPR per l'ambiente di Test Comuni è https://wstest.anpr.interno.it, quello che avete inserito https://dptest.anpr.interno.it/combas è relativo all'accesso all'applicazione web di ANPR con le credenziali.
Provate a specificare il corretto endpoint e riprovate.
Cordiali saluti

**Comment by gife67** [comment]
Buongiorno, 
non avendo avuto un riscontro per ora chiudo la issue, nel caso potete riaprirne una nuova per avere supporto.
Cordiali saluti
