### ISSUE TITLE
[TEST CONNESSIONE ambiente di pre-subentro e produzione

### ISSUE THREAD

**Issue by adrianosicilia** [italia/anpr#2632]
Grazie della collaborazione, sono Adriano Sicilia, per conto del comune di Rende-CS (078102)
dopo aver validato i file di ANPR e AIRE nella piattaforma web in fase di PRE-SUBENTRO,  troviamo difficoltà ad instaurare il TEST di Connessione  con i webservices, sia in ambiente di presubentro che produzione.
nel progetto maven ho creato le cartelle e i file per gli ambienti  FREE, TEST, PRE, PROD
in particolare
nella cartella config ho inserito     
FREE_Keystore.properties,    TEST_Keystore.properties,       PRE_Keystore.properties,      PROD_Keystore.properties
nella cartella keystore ho inserito i certificati per i relativi ambienti  
888198-CO-0000.p12,          078102-CO-0000.p12,             078102-PC-0001.p12,           078102-PC-0001.p12

ma quando effettuo le chiamate negli ambienti free e test, tutto ok, mentre per il pre e prod non riesco ad effettuare nemmeno il test di connessione 
ottengo:
questa è la request da inviare:
<?xml version="1.0"?>
<ns2:RichiestaConnessione xmlns:ns2="http://sogei.it/ANPR/connessione">
<testataRichiesta>
<idOperazioneComune>20210426123547</idOperazioneComune>
<codMittente>078102</codMittente>
<codDestinatario>ANPR02</codDestinatario>
<operazioneRichiesta>CONN</operazioneRichiesta>
<dataOraRichiesta>2021-04-26T10:35:47.000+01:00</dataOraRichiesta>
<tipoOperazione>V</tipoOperazione>
<tipoInvio>PROD</tipoInvio>
<nomeApplicativo>Aquarius MAVEN</nomeApplicativo>
<versioneApplicativo>2019.1</versioneApplicativo>
<fornitoreApplicativo>Aquarius sas</fornitoreApplicativo>
</testataRichiesta>
</ns2:RichiestaConnessione>

questo è il log della richiesta:
F:\ANPR_Client>java -cp tool-testconn-1.3.0.jar;. it.interno.anpr.security.main.RunSenderMessage PROD TESTCONN request\0\0_078102_PROD.req  
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [it.interno.anpr] additivity to [false].
log4j: Level value for it.interno.anpr is  [DEBUG].
log4j: it.interno.anpr level set to DEBUG
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n].
log4j: Adding appender named [console] to category [it.interno.anpr].
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Adding appender named [console] to category [root].
2021-04-26 12:44:52 INFO  BusApplicationContext:510 - Refreshing org.apache.cxf.bus.spring.BusApplicationContext@3e9b1010: startup date [Mon Apr 26 12:44:52 CEST 2021]; root of context hierarchy
2021-04-26 12:44:52 INFO  BusApplicationContext:449 - Loaded configuration file cxf.xml.
2021-04-26 12:44:52 INFO  ControlledValidationXmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
2021-04-26 12:44:52 INFO  ControlledValidationXmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [cxf.xml]
2021-04-26 12:44:53 INFO  ReflectionServiceFactoryBean:390 - Creating Service {http://sogei.it/ANPR/TestConn}TestConn from WSDL: jar:file:/F:/ANPR_Client/tool-testconn-1.3.0.jar!/wsdl/testConnettivita.wsdl
2021-04-26 12:44:53 DEBUG ConfigHandler:65 - Key: (URL_WS):https://ws.anpr.interno.it
2021-04-26 12:44:53 INFO  RequestHandler:58 - ENDPOINT=https://ws.anpr.interno.it/ANPRTestConn/TestConn
2021-04-26 12:44:53 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.alias):078102-CO-0000
2021-04-26 12:44:53 INFO  TestConnHandler:40 - testConnessione invoke...
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.alias):078102-CO-0000
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (ID_OPERATORE):BLMFNC70P57D086V
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (ID_SEDE):078102
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (ID_POSTAZIONE):078102-CO-0000
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (ID_POSTAZIONE):078102-CO-0000
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (PATH_KEYSTORE_POSTAZIONE):keystore/PROD/078102-CO-0000.p12
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (PASS_KEYSTORE_POSTAZIONE):*************************************************************
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (ID_APPLICAZIONE):12345
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.alias):078102-CO-0000
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.password):*********************************************************
2021-04-26 12:44:54 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.password):*********************************************************
2021-04-26 12:45:15 WARN  PhaseInterceptorChain:449 - Interceptor for {http://sogei.it/ANPR/TestConn}TestConn#{http://sogei.it/ANPR/TestConn}testConnessione has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Connection timed out: connect
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:221)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	at com.sun.proxy.$Proxy36.testConnessione(Unknown Source)
	at it.interno.anpr.security.message.TestConnHandler.sendRequest(TestConnHandler.java:41)
	at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:47)
	at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:61)
Caused by: com.ctc.wstx.exc.WstxIOException: Connection timed out: connect
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:458)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:777)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:724)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
	... 12 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:236)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1320)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1280)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:267)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
	at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
	at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
	at com.ctc.wstx.sw.BufferingXmlWriter.flushBuffer(BufferingXmlWriter.java:1405)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:281)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:603)
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:456)
	... 15 more
2021-04-26 12:45:15 ERROR TestConnHandler:44 - Exception nell'invio richiesta
javax.xml.ws.soap.SOAPFaultException: Connection timed out: connect
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:161)
	at com.sun.proxy.$Proxy36.testConnessione(Unknown Source)
	at it.interno.anpr.security.message.TestConnHandler.sendRequest(TestConnHandler.java:41)
	at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:47)
	at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:61)
Caused by: com.ctc.wstx.exc.WstxIOException: Connection timed out: connect
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:458)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:777)
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:724)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	... 4 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:236)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1320)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1280)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:267)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
	at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
	at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
	at com.ctc.wstx.sw.BufferingXmlWriter.flushBuffer(BufferingXmlWriter.java:1405)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:281)
	at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:603)
	at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:456)
	... 15 more

spero di essere stato chiaro nel definire il problema .....
saluti, Adriano Sicilia

**Comment by gife67** [comment]
Buongiorno,
per connettersi all'ambiente di Produzione è necessario richiedere l'abilitazione del vostro IP pubblico internet con cui vi presentate alla piattaforma dei servizi ANPR. Questo si fa attraverso l'interfaccia Web di ANPR, in **Amministrazione**, nella sezione che riguarda la gestione dei **Dati del Comune**, su **informazioni aggiuntive**. La trace che avete mandato è relativa ad un tentativo di connessione all'ambiente di Produzione (ws.anpr.interno.it) e ricevete un Connection Timeout perchè il vostro indirizzo IP non è abilitato sui nostri firewall. Per quanto riguarda il problema verso l'ambiente di Presubentro invece non è necessaria l'abilitazione sui nostri firewall, ma vanno utilizzati i certificati e l'utenza di produzione, quindi se mi allega la stessa trace fatta per la produzione le posso fornire maggiori dettagli.
Attendo vostre verifiche,
Giuseppe Ferraro

**Comment by adrianosicilia** [comment]
Buongiorno,
cosa strana, perchè in data 30/04/2021, ho ripetuto i test e in ambiente di pre-subentro, i certificati usati sembra che funzionano, mentre nell'ambienti di subentro, con la configurazione indicata è già presente un indirizzo pubblico, permane ancora l'errore di TimeOut, non vorrei che gli ip dinamici della sotto rete interna vadano indicati pure?
Adriano Sicilia

**Comment by gife67** [comment]
Buongiorno,
ho fatto verificare ed il vostro IP 217.59.135.164 risulta abilitato.
Dovreste verificare esattamente con quali IP uscite su internet e vi presentate alla piattaforma ANPR e richiedere l'abilitazione.
Ovviamente dovreste avere uno o più IP pubblici fisso e non quelli dinamici forniti dal vostro provider, altrimenti dovremo abilitare tutta la classe di indirizzi del provider e questo non lo possiamo fare.

**Comment by gife67** [comment]
Buongiorno,
siccome non ho avuto più un riscontro, chiudo la issue e nel caso vi servisse ulteriore supporto potete riaprirne un altra.
Cordiali saluti.

**Comment by adrianosicilia** [comment]
Buongiorno, completata la fase di SUBENTRO, abbiamo ripreso con lo sviluppo dei ws per allineare le banche dati LOCALE e ANPR, effettuando dei test di connessione che in fase di PRE-SUB funzionavano, ora in PRESUBENTRO riceviamo ancora un time-out con risposta negativa 

"
2021-07-09 09:40:40 DEBUG ConfigHandler:65 - Key: (org.apache.ws.security.crypto.merlin.keystore.password):916295DD
2021-07-09 09:41:01 WARN  PhaseInterceptorChain:449 - Interceptor for {http://sogei.it/ANPR/TestConn}TestConn#{http://sogei.it/ANPR/TestConn}testConnessione has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Connection timed out: connect
"

Controllando il file che viene creato in fase di invio da [**tool-testconn-1.3.0.jar
Duplicate of #**] ho notato che l'indirizzo IP prelevato "192.168.56.1" dalla procedura è quello della lan interna della 1° scheda di rete e non quello pubblico 217.59.135.164 attivo sulla 2° scheda di rete. 

"
 <saml2:AuthnStatement AuthnInstant="2021-07-09T07:40:39.904Z" SessionNotOnOrAfter="2021-07-09T07:45:39.904Z">
                    <saml2:SubjectLocality Address="192.168.56.1"/>
                    <saml2:AuthnContext>
                        <saml2:AuthnContextClassRef/>
                    </saml2:AuthnContext>
                </saml2:AuthnStatement>
"
E' gradito qualsiasi suggerimento atto a risolvere il problema.
Cordiali saluti.

**Comment by gife67** [comment]
Buongiorno,
ho verificato che in ambiente di presubentro abbiamo ricevuto dalle 09:22 alle 09:37 di oggi 5 richieste verso il servizio di TestConn, dall'IP 217.59.135.165 (e non .164 come avete indicato), dalla postazione 078102-PC-0001 con CF = BLM*****86V tutte fallite con Soap Fault "Rejected by policy", che sta ad indicare che c'è un problema nella cornice di sicurezza.
Provo a far mettere una trace per darvi dei dettagli maggiori sul tipo di problema. Se potete inviare ulteriori richieste fra circa 5-10 minuti ed inviarne una ogni minuto, in modo da poter catturare i vostri messaggi. 
Per il connection timeout questo sicuramente è dovuto alla vostra infrastruttura che non propaga i messaggi di soapfault in cui è riportato il messaggio "Rejected by policy"
E' normale che nella SAML ci sia il vostro indirizzo interno, poichè le librerie lo prelevano dal server su cui viene preparata la SAML assertion, non ha alcuna influenza sui filtri di accesso, ma ha solo scopo di Audit.

**Comment by gife67** [comment]
Buongiorno, rettifico ciò che ho indicato nel precedente post, delle 5 richieste 2 erano andate bene, nonostante avessero le stesse caratteristiche delle 3 andate male. Oggi ho verificato che ci sono 2 richieste entrambi andate bene dall'IP 82.62.244.165, con lo stesso certificato di postazione e la stessa utenza.
